### ISSUE TITLE
Planedo Bundle has a dependency to psr/clock@dev

### ISSUE THREAD

**Issue by benjaminkott** [Crell/PlanedoBundle#1]
Package should not require dev dependencies, otherwise, this also needs to be required in the root of the project that uses the bundle or  it needs to set the minimum stability to dev. 

This package also seems to be unreleased to packagist. And cannot be resolved by the project, except it also includes the repository.

```
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/php-fig/clock.git"
        }
    ],
```

Please also see notes in the repository itself.

```
CAVEAT: This is currently Work in Progress!

Do not (I repeat: Do NOT) rely on this interface being stable!

Using this as long as the PSR is not officially released happens at your own risk!
```

**Comment by Crell** [comment]
Now that there's an officially approved and tagged release, this has been fixed in `master`.
