### ISSUE TITLE
Bundle is not compatible with latest Symfony 5.4 LTS version

### ISSUE THREAD

**Issue by benjaminkott** [Crell/PlanedoBundle#2]
Symfony 6 is currently bleeding edge and gets its LTS status in 2024. This means that most libs are not compatible yet and it is not foreseeable when they will get available. For this, we need to provide support for the current LTS version that was released in November 2021. See https://symfony.com/releases for more information.

**Comment by Crell** [comment]
It's been downgraded to 5.4.  Though we may still bump it back to 6.0 at some point, as it's been a while.
